"""`aspose-slides-mcp` — Slides' curated 8-tool MCP surface (Sprint 11, PRD Section 2.6/FR15b).

A genuinely separate, installable, versioned package (zero import dependency on the builder's own
`mcp_builder` — same Requirement 5.1 discipline `aspose-storage-core-mcp` established in Sprint 7,
extended here per Decision 4/Fork 1 Option A). No core/extra split (execution plan Fork 4) — it is
not a shared dependency of any other product, so every curated tool lives here.

Declares a real, ordinary versioned dependency on `aspose-storage-core-mcp` (`pyproject.toml`) for
the bundled core subset (`storage_upload_file`/`storage_download_file`/`storage_list_files`/
`storage_delete_file`, FR15b) — a user connected to only this server can still upload a file and get
its converted download, with no second server connection (this sprint's own exit criterion).
`generated/slides/server.py` is where that bundling actually happens; this package only owns Slides'
own tools.

**Real, live-verified finding (Sprint 11, this session): Slides' real API is `v3.0`, not `v4.0`.**
`GET /v4.0/slides` returns the identical raw-nginx `404` a genuinely nonexistent product namespace
returns — the entire `v4.0` gateway for Slides isn't provisioned (Decision 3 already flagged this in
passing; this session confirmed it conclusively). `v3.0/slides` is fully live with its own real spec.
This package's tools, `generated/slides/server.py`, and `run_lifecycle.py`'s `SLIDES_BASE_URL` are all
built against `v3.0` — the one product-specific exception among this project's products, every other
one confirmed live on `v4.0`. `codegen/spec.py`'s `_SLIDES_OPERATION_SPECS` module comment has the
full per-operation account, including two real generator bugs this rebuild found and fixed
(`_path_expression`'s single-path-parameter assumption, and the upload/download shapes' hardcoded
HTTP verbs) and one real normalizer bug (`_resolve_response_schema` only checking for a `"200"`
status, missing `CreatePresentation`'s real `"201"` success response).

One operation is still deferred under `v3.0`: `Merge` (`POST /slides/{name}/merge`) — its only way to
name merge sources is a required `in: body` `request` parameter, the same unsupported shape Words'
Fork 7 and Cells' own build both deferred elsewhere.

Regenerated by the builder's Codegen agent (`mcp_builder.codegen`) from the tracked, curated-subset
Slides IR — never hand-patched (rubric gate 8).
"""

from __future__ import annotations

from aspose_slides_mcp import tools
from aspose_slides_mcp.tools import (
    CreatePresentationResponse,
    GetDocumentPropertiesResponse,
    GetPresentationImagesResponse,
    GetPresentationTextItemsResponse,
    GetSlidesResponse,
    ReplacePresentationTextResponse,
    SplitResponse,
    slides_create_presentation,
    slides_download_presentation,
    slides_get_presentation_properties,
    slides_get_text_items,
    slides_list_images,
    slides_list_slides,
    slides_replace_text,
    slides_split_presentation,
)

TOOL_ANNOTATIONS: dict[str, dict[str, object]] = {
    "slides_download_presentation": {
        "title": "Download an existing Cloud-stored presentation in a given format",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "slides_create_presentation": {
        "title": "Create a new presentation in Aspose Cloud Storage",
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
    "slides_get_presentation_properties": {
        "title": "Get a presentation's document properties",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "slides_split_presentation": {
        "title": "Split a presentation into separate slide files",
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "slides_replace_text": {
        "title": "Replace text throughout a presentation",
        "read_only_hint": False,
        "destructive_hint": False,
        "idempotent_hint": False,
        "open_world_hint": True,
    },
    "slides_list_slides": {
        "title": "List a presentation's slides",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "slides_list_images": {
        "title": "List a presentation's images",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
    "slides_get_text_items": {
        "title": "Get all text items in a presentation",
        "read_only_hint": True,
        "destructive_hint": False,
        "idempotent_hint": True,
        "open_world_hint": True,
    },
}

__all__ = [
    "tools",
    "slides_download_presentation",
    "slides_create_presentation",
    "slides_get_presentation_properties",
    "slides_split_presentation",
    "slides_replace_text",
    "slides_list_slides",
    "slides_list_images",
    "slides_get_text_items",
    "CreatePresentationResponse",
    "GetDocumentPropertiesResponse",
    "GetPresentationImagesResponse",
    "GetPresentationTextItemsResponse",
    "GetSlidesResponse",
    "ReplacePresentationTextResponse",
    "SplitResponse",
    "TOOL_ANNOTATIONS",
]
