"""`aspose-slides-mcp`'s own standalone, runnable MCP server.

Auto-generated by Codegen's `generate_server_module_source` from the tracked IR — regenerate via
`run_lifecycle.py --product slides --action rebuild` instead of patching this file directly
(rubric gate 8: hand-patched generated output is a hard-gate failure, same discipline this
package's own `tools.py` header states).

This is the real runnable entry point the public `aspose-slides-mcp` package ships. Before
this file existed, the only actual MCP server for this product lived inside the private builder
repo's own staging area (its `generated/slides/server.py`), which imports the builder's own
internal auth client, tool-spec builder, IR document schema, lessons store, and semantic-db
modules directly, and loaded a live `ir/slides/*.json` snapshot at import time just to
recompute each tool's annotations and structured-output flag. None of that exists once this
package is the only thing actually published (Decision 6: every "published" release so far has
only ever been a GitLab tag of the *tools library*, `tools.py` — never a runnable server) — so
this file is a deliberate, self-contained rendering with **zero import dependency on the private
builder package**, mirroring every other file in this package's own zero-import-dependency-on-
the-builder discipline (see this package's own `_auth.py`/`_path_resolution.py` docstrings).
Every tool's annotations and
`structured_output` flag are baked into this file as literal values at the time it was
generated — never recomputed from a live IR file at server startup, since no IR file ships with
this package.

Bundles Storage's core-4 tools (FR15b) exactly like the existing staging-area servers do, so a
user connected to only this server can upload a file, operate on it, and download the result
with no second server connection.
"""

from __future__ import annotations

from typing import Any

from aspose_storage_core_mcp import (
    DeleteFileResponse,
    storage_delete_file,
    storage_download_file,
    storage_list_files,
    storage_upload_file,
)
from aspose_slides_mcp import (
    CreatePresentationResponse,
    GetDocumentPropertiesResponse,
    GetPresentationImagesResponse,
    GetPresentationTextItemsResponse,
    GetSlidesResponse,
    ReplacePresentationTextResponse,
    SplitResponse,
    slides_create_presentation,
    slides_download_presentation,
    slides_get_presentation_properties,
    slides_get_text_items,
    slides_list_images,
    slides_list_slides,
    slides_replace_text,
    slides_split_presentation,
)
from aspose_slides_mcp._auth import AsposeAuthClient
from mcp.server.mcpserver import MCPServer
from mcp_types import ToolAnnotations


server = MCPServer(
    "aspose-slides",
    version="0.1.0",
    instructions="Real Codegen-generated MCP tools for Slides' curated operation set, plus Storage's bundled core subset (upload/download/list/delete).",
)


_auth: AsposeAuthClient | None = None


def _get_auth() -> AsposeAuthClient:
    global _auth
    if _auth is None:
        _auth = AsposeAuthClient()
    return _auth


# --- Bundled Storage core subset (FR15b) ----------------------------------------------------


def storage_upload_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, content_base64: str | None = None, dry_run: bool = False) -> dict[str, Any]:
    # Sprint 11 real bug fix: `storage_upload_file`/`storage_delete_file` gained a `base_url`
    # parameter (Slides' v3.0 finding) inserted *before* `dry_run` in their real signatures -- a
    # positional call here would have silently passed `dry_run`'s value into `base_url` instead
    # (a real, confirmed bug, never actually exercised until now). Every storage-core call below is
    # keyword-only from this point on, immune to any future parameter reordering.
    return storage_upload_file(_get_auth(), "slides", filename, version_id=version_id, storage_name=storage_name, content_base64=content_base64, dry_run=dry_run)


def storage_download_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    return storage_download_file(_get_auth(), "slides", filename, version_id=version_id, storage_name=storage_name, output_filename=output_filename, return_base64=return_base64)


def storage_list_files_tool(folder_name: str | None = None, storage_name: str | None = None) -> dict[str, Any]:
    return storage_list_files(_get_auth(), "slides", folder_name=folder_name, storage_name=storage_name)


def storage_delete_file_tool(filename: str, version_id: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> DeleteFileResponse:
    return storage_delete_file(_get_auth(), "slides", filename, version_id=version_id, storage_name=storage_name, dry_run=dry_run)


_STORAGE_ANNOTATIONS = {
    "storage_upload_file": {"title": "Upload a file to Aspose Cloud Storage", "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False},
    "storage_download_file": {"title": "Download a file from Aspose Cloud Storage", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True},
    "storage_list_files": {"title": "List files in an Aspose Cloud Storage folder", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True},
    "storage_delete_file": {"title": "Delete a file from Aspose Cloud Storage", "read_only_hint": False, "destructive_hint": True, "idempotent_hint": True},
}


_STORAGE_WRAPPERS = {
    "storage_upload_file": storage_upload_file_tool,
    "storage_download_file": storage_download_file_tool,
    "storage_list_files": storage_list_files_tool,
    "storage_delete_file": storage_delete_file_tool,
}

_STORAGE_REAL_FUNCS = {
    "storage_upload_file": storage_upload_file,
    "storage_download_file": storage_download_file,
    "storage_list_files": storage_list_files,
    "storage_delete_file": storage_delete_file,
}


# --- Slides' own curated tools ------------------------------------------------------------


def slides_create_presentation_tool(filename: str, folder_name: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> CreatePresentationResponse:
    return slides_create_presentation(_get_auth(), filename=filename, folder_name=folder_name, storage_name=storage_name, dry_run=dry_run)


def slides_download_presentation_tool(filename: str, target_format: str, folder_name: str | None = None, storage_name: str | None = None, fonts_folder_name: str | None = None, slide_indices: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    return slides_download_presentation(_get_auth(), filename=filename, target_format=target_format, folder_name=folder_name, storage_name=storage_name, fonts_folder_name=fonts_folder_name, slide_indices=slide_indices, output_filename=output_filename, return_base64=return_base64)


def slides_split_presentation_tool(filename: str, target_format: str | None = None, width: str | None = None, height: str | None = None, from_slide: str | None = None, to_slide: str | None = None, destination_folder_name: str | None = None, storage_name: str | None = None, folder_name: str | None = None, fonts_folder_name: str | None = None, dry_run: bool = False) -> SplitResponse:
    return slides_split_presentation(_get_auth(), filename=filename, target_format=target_format, width=width, height=height, from_slide=from_slide, to_slide=to_slide, destination_folder_name=destination_folder_name, storage_name=storage_name, folder_name=folder_name, fonts_folder_name=fonts_folder_name, dry_run=dry_run)


def slides_list_images_tool(filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetPresentationImagesResponse:
    return slides_list_images(_get_auth(), filename=filename, folder_name=folder_name, storage_name=storage_name)


def slides_get_presentation_properties_tool(filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetDocumentPropertiesResponse:
    return slides_get_presentation_properties(_get_auth(), filename=filename, folder_name=folder_name, storage_name=storage_name)


def slides_list_slides_tool(filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetSlidesResponse:
    return slides_list_slides(_get_auth(), filename=filename, folder_name=folder_name, storage_name=storage_name)


def slides_get_text_items_tool(filename: str, with_empty: bool | None = None, folder_name: str | None = None, storage_name: str | None = None) -> GetPresentationTextItemsResponse:
    return slides_get_text_items(_get_auth(), filename=filename, with_empty=with_empty, folder_name=folder_name, storage_name=storage_name)


def slides_replace_text_tool(filename: str, old_value: str, new_value: str, ignore_case: bool | None = None, whole_words_only: bool | None = None, folder_name: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> ReplacePresentationTextResponse:
    return slides_replace_text(_get_auth(), filename=filename, old_value=old_value, new_value=new_value, ignore_case=ignore_case, whole_words_only=whole_words_only, folder_name=folder_name, storage_name=storage_name, dry_run=dry_run)


_PRODUCT_ANNOTATIONS = {
    "slides_create_presentation": {"title": 'Create a new presentation in Aspose Cloud Storage', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": True},
    "slides_download_presentation": {"title": 'Download an existing Cloud-stored presentation in a given format', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "slides_split_presentation": {"title": 'Split a presentation into separate slide files', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "slides_list_images": {"title": "List a presentation's images", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "slides_get_presentation_properties": {"title": "Get a presentation's document properties", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "slides_list_slides": {"title": "List a presentation's slides", "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "slides_get_text_items": {"title": 'Get all text items in a presentation', "read_only_hint": True, "destructive_hint": False, "idempotent_hint": True, "open_world_hint": True, "structured_output": True},
    "slides_replace_text": {"title": 'Replace text throughout a presentation', "read_only_hint": False, "destructive_hint": False, "idempotent_hint": False, "open_world_hint": True, "structured_output": True},
}


_PRODUCT_WRAPPERS = {
    "slides_create_presentation": slides_create_presentation_tool,
    "slides_download_presentation": slides_download_presentation_tool,
    "slides_split_presentation": slides_split_presentation_tool,
    "slides_list_images": slides_list_images_tool,
    "slides_get_presentation_properties": slides_get_presentation_properties_tool,
    "slides_list_slides": slides_list_slides_tool,
    "slides_get_text_items": slides_get_text_items_tool,
    "slides_replace_text": slides_replace_text_tool,
}


_PRODUCT_REAL_FUNCS = {
    "slides_create_presentation": slides_create_presentation,
    "slides_download_presentation": slides_download_presentation,
    "slides_split_presentation": slides_split_presentation,
    "slides_list_images": slides_list_images,
    "slides_get_presentation_properties": slides_get_presentation_properties,
    "slides_list_slides": slides_list_slides,
    "slides_get_text_items": slides_get_text_items,
    "slides_replace_text": slides_replace_text,
}


def _register_all_tools() -> None:
    # Storage core subset first (FR15b) — same 4 tools, same annotations, every rendered
    # server bundles.
    for name, wrapper in _STORAGE_WRAPPERS.items():
        annotations = _STORAGE_ANNOTATIONS[name]
        real_description = _STORAGE_REAL_FUNCS[name].__doc__
        server.add_tool(
            wrapper,
            name=name,
            title=annotations["title"],
            description=real_description or annotations["title"],
            annotations=ToolAnnotations(
                title=annotations["title"],
                read_only_hint=annotations["read_only_hint"],
                destructive_hint=annotations["destructive_hint"],
                idempotent_hint=annotations["idempotent_hint"],
                open_world_hint=True,
            ),
            structured_output=True,
        )

    # Slides' own curated tools.
    for name, wrapper in _PRODUCT_WRAPPERS.items():
        annotations = _PRODUCT_ANNOTATIONS[name]
        real_description = _PRODUCT_REAL_FUNCS[name].__doc__
        server.add_tool(
            wrapper,
            name=name,
            title=annotations["title"],
            description=real_description or annotations["title"],
            annotations=ToolAnnotations(
                title=annotations["title"],
                read_only_hint=annotations["read_only_hint"],
                destructive_hint=annotations["destructive_hint"],
                idempotent_hint=annotations["idempotent_hint"],
                open_world_hint=annotations["open_world_hint"],
            ),
            structured_output=annotations["structured_output"],
        )


_register_all_tools()


def main() -> None:
    server.run(transport="stdio")


if __name__ == "__main__":
    main()
