"""Auto-generated by Codegen (FR4) from the tracked IR — do not edit by hand.

Regenerate via `run_lifecycle.py --product slides --action rebuild` instead of patching this file directly (rubric gate 8: hand-patched generated output is a hard-gate failure).
"""

from __future__ import annotations

from typing import Any, TypedDict

import requests

from aspose_slides_mcp._auth import AsposeAuthClient
from aspose_slides_mcp._path_resolution import resolve_local_path
from aspose_slides_mcp._errors import ToolError, call_with_taxonomy

BASE_URL = "https://api.aspose.cloud/v3.0"


class CreatePresentationResponse(TypedDict, total=False):
    DocumentProperties: dict
    ViewProperties: dict
    Slides: dict
    Images: dict
    LayoutSlides: dict
    MasterSlides: dict
    SelfUri: dict
    AlternateLinks: list


class SplitResponse(TypedDict, total=False):
    Slides: list
    SelfUri: dict
    AlternateLinks: list


class GetPresentationImagesResponse(TypedDict, total=False):
    List: list
    SelfUri: dict
    AlternateLinks: list


class GetDocumentPropertiesResponse(TypedDict, total=False):
    List: list
    SelfUri: dict
    AlternateLinks: list


class GetSlidesResponse(TypedDict, total=False):
    SlideList: list
    SelfUri: dict
    AlternateLinks: list


class GetPresentationTextItemsResponse(TypedDict, total=False):
    Items: list
    SelfUri: dict
    AlternateLinks: list


class ReplacePresentationTextResponse(TypedDict, total=False):
    Matches: int
    DocumentProperties: dict
    ViewProperties: dict
    Slides: dict
    Images: dict
    LayoutSlides: dict
    MasterSlides: dict
    SelfUri: dict
    AlternateLinks: list


def slides_create_presentation(auth: AsposeAuthClient, filename: str, folder_name: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> CreatePresentationResponse:
    'Creates a new presentation in Aspose Slides, optionally using an uploaded source file as a template and optionally applying a password to the new file.  \n\nname (path, required, string): the filename for the presentation to be created (e.g.,\u202f“MyDeck.pptx”).  \n\ndata (formData, optional, file): binary content of an existing presentation to use as a base; must be a supported presentation format such as\u202f.pptx,\u202f.ppt,\u202f.odp.  \n\ninputPassword (header, optional, string): password for opening the source presentation supplied in\u202f*data* if it is encrypted.  \n\npassword (header, optional, string): password to protect the newly created presentation; if omitted the new file is not password‑protected.  \n\nfolder (query, optional, string): path to the folder in the selected storage where the new presentation will be saved; defaults to the root folder if omitted.  \n\nstorage (query, optional, string): name of the Aspose Cloud storage to use; if omitted the default storage is used.  \n\nReturns a JSON object describing the created presentation with the fields **DocumentName** (string), **Href** (string URL to the created file), **Size** (integer\u202f– file size in bytes), **SlidesCount** (integer), and **PasswordProtected** (boolean).'
    params = {k: v for k, v in {"folder": folder_name, "storage": storage_name}.items() if v is not None}
    url = f"/slides/{filename}"
    if dry_run:
        return {"dry_run": True, "operation": "CreatePresentation"}
    response = call_with_taxonomy(lambda: requests.post(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def slides_download_presentation(auth: AsposeAuthClient, filename: str, target_format: str, folder_name: str | None = None, storage_name: str | None = None, fonts_folder_name: str | None = None, slide_indices: str | None = None, output_filename: str | None = None, return_base64: bool = False) -> dict[str, Any]:
    'This tool retrieves a presentation from Aspose Slides Cloud and exports it to the requested format, returning the file data for download.  \n\n- **name** – path parameter, required, string: the exact filename of the source presentation (including extension).  \n- **format** – path parameter, required, string: the target export format (e.g., “pdf”, “png”, “pptx”; any format supported by Aspose Slides).  \n- **options** – body parameter, optional, object: a JSON object containing format‑specific export options as defined by the Aspose Slides API.  \n- **password** – header parameter, optional, string: password to open the source presentation if it is protected.  \n- **folder** – query parameter, optional, string: the cloud folder path where the source presentation resides; defaults to the root if omitted.  \n- **storage** – query parameter, optional, string: the name of the Aspose Cloud storage to use; if omitted the default storage is used.  \n- **fontsFolder** – query parameter, optional, string: path to a folder containing custom fonts that should be used during export.  \n- **slides** – query parameter, optional, string: a comma‑separated list of slide indices to export (e.g., “1,3,5”); if omitted all slides are exported.  \n\nThe tool returns the exported presentation as binary data (typically base64‑encoded) together with the HTTP status indicating success or error.'
    params = {k: v for k, v in {"folder": folder_name, "storage": storage_name, "fontsFolder": fonts_folder_name, "slides": slide_indices}.items() if v is not None}
    url = f"/slides/{filename}/{target_format}"
    response = call_with_taxonomy(lambda: requests.post(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    if return_base64:
        import base64 as _base64
        return {"content_base64": _base64.b64encode(response.content).decode("ascii")}
    local_path = resolve_local_path(output_filename or filename, is_output=True)
    local_path.write_bytes(response.content)
    return {"Status": "OK", "local_path": str(local_path)}


def slides_split_presentation(auth: AsposeAuthClient, filename: str, target_format: str | None = None, width: str | None = None, height: str | None = None, from_slide: str | None = None, to_slide: str | None = None, destination_folder_name: str | None = None, storage_name: str | None = None, folder_name: str | None = None, fonts_folder_name: str | None = None, dry_run: bool = False) -> SplitResponse:
    'The tool splits a PowerPoint presentation into separate image files, generating one image for each selected slide and uploading the images to a storage folder.\n\n- **name** (path, string, required): the filename of the presentation to split.  \n- **options** (body, object, optional): an export‑options object defined by Aspose that can customize image generation.  \n- **format** (query, string, optional, default\u202f=\u202f"jpeg"): the image format for the output files (e.g., "jpeg", "png", "bmp", "gif", "tiff").  \n- **width** (query, integer, optional): the width in pixels of each generated image.  \n- **height** (query, integer, optional): the height in pixels of each generated image.  \n- **from** (query, integer, optional): the 1‑based slide number to start splitting from; if omitted, splitting starts with the first slide.  \n- **to** (query, integer, optional): the 1‑based slide number to end splitting at; if omitted, splitting continues through the last slide.  \n- **destFolder** (query, string, optional): the storage folder path where the generated images will be uploaded; if omitted, images are stored in the same folder as the source presentation.  \n- **password** (header, string, optional): password for opening a protected presentation.  \n- **folder** (query, string, optional): the storage folder containing the source presentation.  \n- **storage** (query, string, optional): the name of the storage service to use.  \n- **fontsFolder** (query, string, optional): the folder that contains custom fonts required for rendering the slides.\n\nThe tool returns a JSON object whose main field is an array of strings, each string being the path (or URL) of an uploaded image file representing a split slide.'
    params = {k: v for k, v in {"format": target_format, "width": width, "height": height, "from": from_slide, "to": to_slide, "destFolder": destination_folder_name, "storage": storage_name, "folder": folder_name, "fontsFolder": fonts_folder_name}.items() if v is not None}
    url = f"/slides/{filename}/split"
    if dry_run:
        return {"dry_run": True, "operation": "Split"}
    response = call_with_taxonomy(lambda: requests.post(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def slides_list_images(auth: AsposeAuthClient, filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetPresentationImagesResponse:
    'Retrieves metadata for every image that is embedded in a specified PowerPoint presentation stored in Aspose Cloud.\n\n- **name** – required path parameter, string; the exact file name of the presentation (including extension, e.g., “deck.pptx”). Must be a non‑empty string.  \n- **password** – optional header parameter, string; password used to open an encrypted presentation. Any non‑empty string is accepted.  \n- **folder** – optional query parameter, string; the path to the folder in the chosen storage where the presentation resides. If omitted the root folder is assumed.  \n- **storage** – optional query parameter, string; the name of the Aspose Cloud storage service (e.g., “MyStorage”). Any non‑empty string is accepted.\n\nThe tool returns a JSON object whose top‑level property is an array (e.g., “Images”) containing one entry per image, each entry providing details such as the image’s index, format, width, height, and any other available image metadata.'
    params = {k: v for k, v in {"folder": folder_name, "storage": storage_name}.items() if v is not None}
    url = f"/slides/{filename}/images"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def slides_get_presentation_properties(auth: AsposeAuthClient, filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetDocumentPropertiesResponse:
    'Retrieves the metadata properties of a PowerPoint presentation file stored in Aspose Slides Cloud.  \n\n- **name** – required string, provided as the `{name}` segment of the URL path, representing the presentation file name.  \n- **password** – optional string, passed in the `password` HTTP header, used when the presentation is password‑protected.  \n- **folder** – optional string, supplied as a query parameter `folder`, indicating the cloud folder that contains the file.  \n- **storage** – optional string, supplied as a query parameter `storage`, specifying the cloud storage name where the file resides.  \n\nReturns a JSON object containing the document’s properties, each entry including the property name, its value, and its data type.'
    params = {k: v for k, v in {"folder": folder_name, "storage": storage_name}.items() if v is not None}
    url = f"/slides/{filename}/documentproperties"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def slides_list_slides(auth: AsposeAuthClient, filename: str, folder_name: str | None = None, storage_name: str | None = None) -> GetSlidesResponse:
    'Retrieves information about all slides in a specified PowerPoint presentation stored in Aspose Cloud.  \n\n- **name** (path, string, required): the exact filename of the presentation, including its extension (e.g.,\u202f“presentation.pptx”).  \n- **password** (header, string, optional): the password to open the presentation if it is password‑protected; omit if not needed.  \n- **folder** (query, string, optional): the path to the folder in the chosen storage where the presentation file resides; if omitted the root folder is assumed.  \n- **storage** (query, string, optional): the name of the Aspose Cloud storage to use; if omitted the default storage is used.  \n\nReturns a JSON object whose top‑level property “Slides” is an array of slide objects, each containing the slide’s Id, Width, Height, and related metadata as defined by the GetSlides endpoint.'
    params = {k: v for k, v in {"folder": folder_name, "storage": storage_name}.items() if v is not None}
    url = f"/slides/{filename}/slides"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def slides_get_text_items(auth: AsposeAuthClient, filename: str, with_empty: bool | None = None, folder_name: str | None = None, storage_name: str | None = None) -> GetPresentationTextItemsResponse:
    'Extracts all text items from a specified PowerPoint presentation file.  \n\n- **name** – required string placed in the URL path; the exact filename of the presentation (e.g., “example.pptx”).  \n- **withEmpty** – optional boolean query parameter; set to true to include empty text items, false or omitted to exclude them.  \n- **password** – optional string header; the password needed to open a protected presentation, if any.  \n- **folder** – optional string query parameter; the path to the folder in storage where the presentation resides.  \n- **storage** – optional string query parameter; the name of the storage service containing the file.  \n\nThe tool returns a JSON object containing a “textItems” array, where each element describes a extracted text item (including its text content and related slide information).'
    params = {k: v for k, v in {"withEmpty": with_empty, "folder": folder_name, "storage": storage_name}.items() if v is not None}
    url = f"/slides/{filename}/textItems"
    response = call_with_taxonomy(lambda: requests.get(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})


def slides_replace_text(auth: AsposeAuthClient, filename: str, old_value: str, new_value: str, ignore_case: bool | None = None, whole_words_only: bool | None = None, folder_name: str | None = None, storage_name: str | None = None, dry_run: bool = False) -> ReplacePresentationTextResponse:
    'Replaces every occurrence of a specified text string in a Slides presentation with a new string.  \n- name (path, string, required): exact filename of the presentation (including extension) as stored in the chosen storage.  \n- oldValue (query, string, required): text to be searched for; must be a non‑empty string.  \n- newValue (query, string, required): text that will replace each occurrence of **oldValue**; may be an empty string to delete the found text.  \n- ignoreCase (query, boolean, optional): true to perform a case‑insensitive search, false (default) to match case‑sensitively.  \n- wholeWordsOnly (query, boolean, optional): true to replace only whole‑word matches of **oldValue**, false (default) to also replace substrings within larger words.  \n- password (header, string, optional): password for opening an encrypted presentation; omit if the file is not protected.  \n- folder (query, string, optional): path to the folder in the storage where the presentation resides; omit for the root folder.  \n- storage (query, string, optional): name of the Aspose Cloud storage to use; if omitted the default storage is assumed.  \nThe tool returns a single JSON object containing a numeric `code`, a string `status`, a string `message` describing the result, and, on success, a `presentation` object with fields `id` (string), `name` (string), `size` (integer, bytes), `width` (number), `height` (number) and `slidesCount` (integer).'
    params = {k: v for k, v in {"oldValue": old_value, "newValue": new_value, "ignoreCase": ignore_case, "wholeWordsOnly": whole_words_only, "folder": folder_name, "storage": storage_name}.items() if v is not None}
    url = f"/slides/{filename}/replaceText"
    if dry_run:
        return {"dry_run": True, "operation": "ReplacePresentationText"}
    response = call_with_taxonomy(lambda: requests.post(
        f"{BASE_URL}{url}",
        params=params,
        headers={"Authorization": auth.get_authorization_header()},
        timeout=30.0,
    ))
    return (response.json() if response.text else {})
